version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: nest-store-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: nest
      POSTGRES_PASSWORD: nest
      POSTGRES_DB: nest_store
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
